// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Game: typeof import('./src/views/Game/index.vue')['default']
    Lobby: typeof import('./src/views/Lobby/index.vue')['default']
    Start: typeof import('./src/views/Start/index.vue')['default']
  }
}

export { }
